name: Slack Topic Monitor
description: Keeping Slack channel topics in line.
inputs:
  owner:
    description: Owner portion of GitHub repo URL
    required: true
  repo:
    description: Repo portion of GitHub repo URL
    required: true
  path:
    description: path for the Slack channels and topics JSON file
    required: true
  SLACK_API_TOKEN:
    description: Slack API key
    required: true
  GITHUB_TOKEN:
    description: GitHub API key
    required: true
  dryRun:
    description: Set this to avoid actually updating Slack channel topics. View the logs!
    default: 'false'
runs:
  using: node16
  main: dist/index.js
